config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :user, except: [:new]

  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  get 'signup', to: 'users#new'
  get 'users', to: 'users#new'
  post 'users', to: 'users#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body,
            presence: true, 
            length: { minimum: 3, maximum: 300 }
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 15 }
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custom_display
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast 'chatroom_channel',
                                    mod_message: message_render(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]
  
  def new
    redirect_to root_path if logged_in?
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to root_path
    else
      flash.now[:error] = 'There was something wrong ' \
        'with your login information'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have logged out'
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = 'You are already logged in'
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the chatroom, #{@user.username}"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange inverted coffee icon"></i>
  Say Something
</h4>

<div class="ui stackable two column grid">
  <div class="twelve wide column">
    <div class="ui card fluid raised chatbox">
      <div class="content scrollable" id="messages">
        <div class="ui feed" id="messageContainer">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content message-form">
        <%= form_with model: @message, 
                      class: 'ui reply form',
                      role: 'form',
                      local: false,
                      url: message_path do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, placeholder: 'Enter a message' %>
              <%= f.button '<i id="submitButton" class="bordered inverted orange edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui fluid inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="ui two column centered grid flashbox">
    <div class="column">
      <div class='ui <%= "#{name}" %> message'>
        <i href="#" class="close icon" data-dismiss="alert"></i>
        <%= content_tag :div, msg, :id => "flash_#{name}", class: 'header' if msg.is_a?(String) %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<div class="ui inverted small menu">
  <div class="ui container">
    <%= link_to 'Chatroom', root_path, class: 'item' %>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <%= link_to 'Log out', logout_path, method: :delete, class: 'item' if logged_in? %>
          <%= link_to 'Log in', login_path, class: 'item' if !logged_in? %>
          <%= link_to 'Sign up', signup_path, class: 'item' if !logged_in? %>
        </div>
      </div>
      <% if !logged_in? %>
        <div class="item">
          <%= link_to "Log in", login_path, class: "ui primary button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/flash' %>
    <div class='ui container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em>
        <%= message.user.username %>
      </em>
    </div>
    <div class="extra text">
      <%= message.body %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="ui error message">
    <i class="close icon"></i>
    <div class="header">
      <%= pluralize(obj.errors.count, "error") %>
      prohibited this article from being saved:
      <ul class="list">
        <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange inverted user icon"></i>
  Create an Accout
</h4>

<%= render 'shared/errors', obj: @user %>
<div class="ui grid">
  <div class="four wide centered column signup-form">
    <%= form_with model: @user, 
                  local: true, 
                  class: "ui form", 
                  role: 'form' do |f| %>
      <div class="ui form">
        <div class="field">
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: "Username", autofocus: true %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <div class="ui left icon input">
            <%= f.password_field :password, placeholder: "Password" %>
            <i class="lock icon"></i>
          </div>
        </div>
        <%= f.button "Create my account", class: "ui orange submit button" %>
      </div>
    <% end %>  
  </div>
</div>